import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const runtime=readFileSync(new URL('../app/living-globe.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../assets/css/command-deck.css',import.meta.url),'utf8');
for(const marker of['living-globe','globe-weather','globe-state','globe.gl@2.45.0','app/living-globe.js'])assert.match(html,new RegExp(marker));
for(const behavior of['Northeast US','New York','Chicago','Atlanta','Los Angeles','Dallas','Toronto','Mexico City','São Paulo','Brazil','Southern England','London','Paris','San Juan','Panama City','Dubai','Bangkok','Thailand','Tokyo','Singapore','Sydney','Lagos','Nigeria','Johannesburg','South Africa','25.2048','55.2708','api.open-meteo.com','onPointClick','autoRotate','prefers-reduced-motion','sessionStorage','pointOfView','WEATHER UNAVAILABLE','earthTelemetry','axialTilt','declination','subsolarLongitude','earthRotation','seasonFor','UTC LOCKED','replaceChildren','fallback\\(\\);selectPoint'])assert.match(runtime,new RegExp(behavior));
assert.equal((runtime.match(/relationship:/g)||[]).length,21);
for(const contract of['\\.globe-ready','\\.globe-fallback','\\.globe-terminator','\\.weather-readout'])assert.match(css,new RegExp(contract));
for(const contract of['\\.earth-linked','earth-live-rotation','\\.earth-orbit-readout','--earth-phase','--earth-axis'])assert.match(css,new RegExp(contract));
assert.doesNotMatch(runtime,/api[_-]?key|secret/i);
console.log('XGS Living Earth runtime tests passed');
