export const nav=[['today','⌂','Today'],['integration','⟲','Integrate'],['academy','◫','Academy'],['globe','◎','Globe'],['intelligence','◇','Intel'],['xmi','♫','XMI'],['missions','△','Mission'],['evolution','↗','Build'],['radar','◌','Radar'],['timeline','│','Timeline'],['archive','≡','Archive']];
export const priorities=[
 {id:'p1',title:'Complete the Academy minimum',detail:'Resume saved lessons: Typing for twelve minutes, then Spanish for eight. Do not restart.',urgency:'Prime'},
 {id:'p2',title:'Move one evidence gate',detail:'Inspect the current Alpha One activation criterion and record one defensible outcome, blocker and continuation.',urgency:'High'},
 {id:'p3',title:'Protect the Sunday rhythm',detail:'Use the dry morning deliberately; keep schedule, movement and personal evidence outside public source.',urgency:'Ongoing'}];
export const courses=[
 {id:'ai',name:'Applied AI',mission:'Build with the system',lesson:'Evidence-based evaluation',status:'Local state only',neglect:'Unknown'},
 {id:'finance',name:'Financial Intelligence',mission:'Money Tree',lesson:'Margin under energy pressure',status:'Local state only',neglect:'Unknown'},
 {id:'spanish',name:'Spanish',mission:'Everyday fluency',lesson:'High-frequency speaking loop',status:'Local state only',neglect:'Unknown'},
 {id:'typing',name:'Typing',mission:'Frictionless input',lesson:'Accuracy before speed',status:'Local state only',neglect:'Priority'}];
export const intelligence=[
 {id:'i1',category:'World',title:'Energy-route risk remains an operating variable',summary:'Recent AP and IMF reporting links conflict-zone energy disruption to slower growth and higher inflation.',why:'Fuel, freight, insurance and working-capital pressure can move together.',consequence:'Landed-cost uncertainty can outlast a single market session.',action:'Shorten quote validity where exposure is real and keep alternatives visible.',confidence:'Medium',freshness:'Jul 26 · source rechecked',state:'Fresh linked context',source:'https://apnews.com/article/e3d8a239509abb50757f8c8d42fb32d8'},
 {id:'i2',category:'Business',title:'Sunday is for evidence, not an invented market',summary:'U.S. cash markets are closed; no live Sunday quote is asserted.',why:'Weekend narrative is not an executable price.',consequence:'A stale number can create false precision in cost or demand decisions.',action:'Use Friday’s authoritative close for context and recheck after Monday’s open.',confidence:'High',freshness:'Weekend state · Jul 26',state:'Truthful unavailable state',source:'https://finance.yahoo.com/quote/SPY/'},
 {id:'i3',category:'Weather',title:'A mostly sunny, dry Sunday supports movement',summary:'The NWS New York Sunday story calls for low-to-mid 80s, light winds and dry conditions; a nearby point forecast shows 81°F / 57°F.',why:'The day offers a clean mobility and recovery window.',consequence:'Outdoor movement is easiest before peak warmth without a storm constraint.',action:'Move early, hydrate, then protect the Academy block.',confidence:'High',freshness:'NWS · Jul 26',state:'Fresh source checked',source:'https://beta.weather.gov/place/CT/Wilton/'},
 {id:'i4',category:'Markets',title:'Weekend market posture is closed and non-executable',summary:'No current cash-market session is active at publication time.',why:'Truthful unavailability is more useful than a recycled quote.',consequence:'Operating assumptions should not be changed from a weekend snapshot.',action:'Recheck authoritative prices Monday before acting.',confidence:'High',freshness:'Sunday · Jul 26',state:'Unavailable by market schedule',source:'https://finance.yahoo.com/quote/SPY/'},
 {id:'i5',category:'Sports',title:'Mets afternoon; Yankees prime time',summary:'Dodgers–Mets is scheduled for 1:40 PM EDT; Yankees–Phillies for 7:20 PM EDT on NBC/Peacock.',why:'These are the two meaningful New York baseball windows.',consequence:'Choose one deliberately after the Academy minimum.',action:'Watch one complete window or use a short recap—avoid ambient distraction.',confidence:'High',freshness:'Schedule · Jul 26',state:'Fresh schedule checked',source:'https://www.mlb.com/schedule/2026-07-26'},
 {id:'i6',category:'Water Cooler',title:'Neuromancer is entering Apple’s adaptation machine',summary:'Apple TV unveiled a first teaser for the William Gibson adaptation at Comic-Con, with release reported for January 22, 2027.',why:'The original helped define cyberpunk; the adaptation must distinguish itself from decades of works it influenced.',consequence:'It is a useful culture-and-technology conversation with real design stakes.',action:'Conversation angle: “Can the blueprint still feel futuristic after everyone copied it?”',confidence:'Medium',freshness:'Comic-Con · Jul 26',state:'Fresh reporting checked',source:'https://www.apple.com/tv-pr/'}];
export const entertainment=[
 {id:'film',type:'FILM / TONIGHT',title:'The Dink · Apple TV',why:'A light underdog comedy for deliberate Sunday recovery—after Academy.',state:'Live now · Apple TV',watchUrl:'https://tv.apple.com/us/movie/the-dink/umc.cmc.5tugaz9vt498ajn7q64ypaqxn',previewUrl:'https://www.apple.com/tv-pr/news/2026/02/apple-original-films-summer-comedy-the-dink-starring-jake-johnson-mary-steenburgen-and-ed-harris-premieres-globally-july-24/'},
 {id:'music',type:'XMI / SONG OF THE DAY',title:'“Lovely Day” · Bill Withers',why:'Steady optimism for a low-friction Sunday reset.',state:'Demonstration recommendation',watchUrl:'https://music.apple.com/us/search?term=Lovely%20Day%20Bill%20Withers'},
 {id:'longform',type:'LONG-FORM / OPERATOR',title:'Steve Jobs · Stanford commencement',why:'A concise reflection on connecting decisions over time; deliberate wind-down only.',state:'Demonstration recommendation',watchUrl:'https://www.youtube.com/watch?v=UF8uR6Z6KLc'}];
export const risks=[
 {type:'risk',scope:'BUSINESS',level:'High',title:'Dual shipping chokepoints can widen cost uncertainty',body:'Hormuz disruption plus Bab el-Mandeb threats can compound energy, freight and insurance pressure.',action:'Revalidate landed cost and shorten quote validity where exposure is real.'},
 {type:'risk',scope:'SYSTEM',level:'High',title:'A percentage can outrun the evidence',body:'Alpha One architecture and repository runtime are maturing faster than hosted production proof.',action:'Score explicit release criteria only after implementation, tests, synchronization and deployment evidence.'},
 {type:'opp',scope:'STRATEGIC',level:'Now',title:'New evaluation and tracing contracts fit the Alpha One question',body:'Repository-tested XET, XEE and XWR capabilities create a stronger path from activity to auditable evidence.',action:'Apply one bounded evidence rule to Daily Bread and record the result without claiming external production maturity.'}];
export const timeline=[['Now','Orient, hydrate and open the saved Academy lesson'],['Next','Typing 12 minutes + Spanish 8 minutes · resume, never restart'],['Morning','Move outdoors, then complete the non-negotiable learning block'],['Midday','Inspect one Alpha One activation criterion'],['Afternoon','Record evidence, blocker and exact continuation'],['Evening','Choose one baseball window or The Dink after Academy'],['Wind-down','Store private notes locally and release the field']];
export const evolution=[
 {metric:'2.7.0',title:'Current edition',body:'July 26 Academy-first command, fresh sources, immutable archive and privacy-safe execution loop.',status:'Repository-backed'},
 {metric:'XPS 4.9',title:'Full Academy assessment',body:'Answer entry, grading, retries, score/XP and Resume Anywhere are locally functional.',status:'Locally functional'},
 {metric:'VOICE',title:'Pronunciation assessment scaffold',body:'Microphone permission and voice runtime architecture are present; provider grading is not claimed without runtime evidence.',status:'Permission-gated'},
 {metric:'XER',title:'Privacy-bounded quality telemetry',body:'Aggregate clicks, recovery categories and control outcomes may be observed; answer text and printable keystrokes are excluded.',status:'Local only'},
 {metric:'FEDERATION',title:'Alpha One evidence sync',body:'Production evidence federation and collision checks feed the Activation Center and fail closed.',status:'Repository-backed'},
 {metric:'WARDEN',title:'Truth before completion',body:'No invented live quotes, private schedules, lesson answers or unsupported percentages are published.',status:'Active'}];
