export const nav=[['today','⌂','Today'],['integration','⟲','Integrate'],['academy','◫','Academy'],['globe','◎','Globe'],['intelligence','◇','Intel'],['xmi','♫','XMI'],['missions','△','Mission'],['evolution','↗','Build'],['radar','◌','Radar'],['timeline','│','Timeline'],['archive','≡','Archive']];
export const priorities=[
 {id:'p1',title:'Complete the Academy minimum',detail:'Resume saved lessons: Typing for twelve minutes, then Spanish for eight. Do not restart.',urgency:'Prime'},
 {id:'p2',title:'Respect the active flood hazards',detail:'Delay unnecessary movement, never enter floodwater, and preserve schedule slack through the afternoon.',urgency:'High'},
 {id:'p3',title:'Advance one verified Alpha 2 gate',detail:'Apply Warden/XER admission; record the evidence, blocker and exact continuation without reopening certified Alpha 1 work.',urgency:'High'}];
export const courses=[
 {id:'ai',name:'Applied AI',mission:'Build with the system',lesson:'Evidence-based evaluation',status:'Local state only',neglect:'Unknown'},
 {id:'finance',name:'Financial Intelligence',mission:'Money Tree',lesson:'Margin under energy pressure',status:'Local state only',neglect:'Unknown'},
 {id:'spanish',name:'Spanish',mission:'Everyday fluency',lesson:'High-frequency speaking loop',status:'Local state only',neglect:'Unknown'},
 {id:'typing',name:'Typing',mission:'Frictionless input',lesson:'Accuracy before speed',status:'Local state only',neglect:'Priority'}];
export const intelligence=[
 {id:'i1',category:'World',title:'Renewed U.S.–Iran escalation reopens energy and shipping risk',summary:'AP reports Iranian missiles targeting U.S. sites in Jordan were intercepted, followed by U.S. and Saudi strikes on Iran-backed militias in Iraq.',why:'The brief de-escalation has broken, restoring uncertainty around Gulf infrastructure and shipping.',consequence:'Oil, freight, insurance and lead times can reprice quickly even before physical supply changes.',action:'Shorten quote-validity assumptions and verify landed costs before commitments.',confidence:'High',freshness:'AP · Jul 29',state:'Fresh source checked',source:'https://apnews.com/article/e31d249ba6443decdd3e63cd00f0fb84'},
 {id:'i2',category:'Technology',title:'Microsoft moves agentic security from assistance toward governed action',summary:'Project Perception introduces specialized red, blue and green security agents with human sign-off for high-impact actions.',why:'The product pattern is continuous agent work bounded by traceable governance—not autonomous theater.',consequence:'Xen’s Warden/XER evidence model aligns with a broader shift toward governed agent execution.',action:'Preserve human approval and replayable evidence at every consequential automation boundary.',confidence:'High',freshness:'Microsoft · Jul 27',state:'Official source checked',source:'https://news.microsoft.com/july-2026-security-news/'},
 {id:'i3',category:'Weather',title:'Flood Advisory and Flood Watch are active this morning',summary:'NWS reports light rain near Danbury at 3:53 AM, a Flood Advisory through 5:45 AM and a Flood Watch through 2:00 PM; showers and thunderstorms may produce another three-quarters to one inch.',why:'Road conditions can degrade before the workday starts and again with afternoon storms.',consequence:'Movement, stopping distance and arrival assumptions need extra margin.',action:'Delay nonessential movement, check hazards before departure and never enter flooded roads.',confidence:'High',freshness:'NWS · Jul 29 · 03:53 EDT',state:'Live hazard checked',source:'https://forecast.weather.gov/MapClick.php?FcstType=text&lat=41.4021&lg=en&lon=-73.4715'},
 {id:'i4',category:'Markets',title:'Broad-market strength masks technology weakness',summary:'Indicative retrieval: SPY $740.86 (+0.19%), QQQ $675.49 (−1.00%), DIA $526.89 (+1.06%), Bitcoin $64,339 (+1.54%).',why:'Rotation and geopolitical oil risk are producing a split market rather than a single risk-on signal.',consequence:'Technology sentiment is weaker even while broader indices and Bitcoin rise.',action:'Treat the pre-open snapshot as context; verify after the cash open and after the Fed decision.',confidence:'Medium',freshness:'Jul 29 · 08:46 UTC',state:'Indicative live retrieval',source:'https://finance.yahoo.com/quote/SPY/'},
 {id:'i5',category:'Sports',title:'Mets play early; Yankees own the evening window',summary:'MLB lists Atlanta at the Mets at 1:10 PM EDT and the Yankees at the White Sox at 7:40 PM EDT.',why:'The games do not compete directly, but Academy and weather remain the gate for leisure.',consequence:'A deliberate midday check or evening watch is possible without surrendering the operating plan.',action:'Resume Academy first; use official watch options only after the minimum is complete.',confidence:'High',freshness:'MLB · Jul 29',state:'Official schedule checked',source:'https://www.mlb.com/schedule?sf103630412=1'},
 {id:'i6',category:'Water Cooler',title:'Oil rebounded while chip stocks kept sliding',summary:'The Guardian’s live business coverage reports Brent near $87.26 after renewed Iran tensions, while global chip weakness continued ahead of the Fed decision.',why:'Geopolitical inflation risk and AI-expectation fatigue are moving markets in opposite directions.',consequence:'The day’s headline index can hide both rising input risk and falling tech appetite.',action:'Conversation angle: “This is a split market—oil risk up, AI expectations down.”',confidence:'High',freshness:'Jul 29',state:'Fresh source checked',source:'https://www.theguardian.com/business/live/2026/jul/29/oil-jumps-iran-surprise-attack-chip-stocks-slump-ai-sell-off-economy-latest-news'}];
export const entertainment=[
 {id:'film',type:'FILM / TONIGHT',title:'The Dink · Apple TV',why:'A light underdog comedy for deliberate recovery—after Academy and the final weather check.',state:'Live now · Apple TV',watchUrl:'https://tv.apple.com/us/movie/the-dink/umc.cmc.5tugaz9vt498ajn7q64ypaqxn',previewUrl:'https://www.apple.com/tv-pr/originals/the-dink/'},
 {id:'music',type:'XMI / SONG OF THE DAY',title:'“Here Comes the Rain Again” · Eurythmics',why:'Weather-matched, cinematic and focused enough for a deliberate reset.',state:'Demonstration recommendation',watchUrl:'https://music.apple.com/us/search?term=Here%20Comes%20the%20Rain%20Again%20Eurythmics'},
 {id:'longform',type:'LONG-FORM / OPERATOR',title:'Project Perception launch',why:'See how a major platform frames continuous agent action with human control and replayable evidence.',state:'Live official source',watchUrl:'https://news.microsoft.com/july-2026-security-news/'}];
export const risks=[
 {type:'risk',scope:'PERSONAL',level:'High',title:'Active flood hazards can disrupt movement and timing',body:'Heavy rain and thunderstorms may create rapid road flooding through the afternoon.',action:'Delay unnecessary travel, preserve stopping distance and never enter flooded roads.'},
 {type:'risk',scope:'BUSINESS',level:'High',title:'Renewed oil risk can shorten valid cost assumptions',body:'Geopolitical escalation has reversed part of the recent energy-price relief.',action:'Recheck freight, fuel and lead-time exposure before long-validity quotes.'},
 {type:'risk',scope:'SYSTEM',level:'High',title:'Repository repair is not proof of live activation',body:'XRE/XRI resilience changes are verified in source, but production state requires runtime evidence.',action:'Keep the activation truth state fail-closed until live receipts pass.'},
 {type:'opp',scope:'STRATEGIC',level:'Now',title:'Governed agent security validates the Xen design direction',body:'Project Perception demonstrates continuous agents with human sign-off and evidence-grade reasoning.',action:'Translate one governance pattern into a testable Alpha 2 acceptance criterion.'}];
export const timeline=[['Now','Check Flood Advisory, hydrate and open saved Academy lessons'],['Next','Typing 12 minutes + Spanish 8 minutes · resume, never restart'],['Morning','Delay nonessential movement until hazard conditions improve'],['Midday','Verify oil, freight and quote-validity assumptions'],['Afternoon','Advance one Warden/XER-admitted Alpha 2 evidence gate'],['Evening','Recheck weather; choose Yankees or The Dink after Academy'],['Wind-down','Record outcome, blocker and exact continuation locally']];
export const evolution=[
 {metric:'2.9.0',title:'Current edition',body:'July 29 hazard-aware Academy command, fresh intelligence, immutable archive and verified release evidence.',status:'Repository-backed'},
 {metric:'XRE/XRI',title:'Resilience and conflict semantics hardened',body:'Canonical source now preserves exact provider evidence, bounded runtime identity and correct split-brain conflict responses.',status:'Repository-backed · live state unclaimed'},
 {metric:'XPS 4.9',title:'Full Academy assessment',body:'Answer entry, grading, retries, score/XP and Resume Anywhere remain locally functional.',status:'Locally functional'},
 {metric:'VOICE',title:'Pronunciation assessment scaffold',body:'Microphone permission architecture is present; provider grading is not claimed without live runtime evidence.',status:'Permission-gated'},
 {metric:'ALPHA 2',title:'Canonical continuation',body:'Alpha 1 remains certified; new work advances through current repository evidence without reopening completed milestones.',status:'Repository-context bounded'},
 {metric:'WARDEN',title:'Truth before completion',body:'No invented hazards, market quotes, private schedules, lesson answers or unsupported percentages are published.',status:'Active'}];
