export const nav=[['today','⌂','Today'],['integration','⟲','Integrate'],['academy','◫','Academy'],['globe','◎','Globe'],['intelligence','◇','Intel'],['xmi','♫','XMI'],['missions','△','Mission'],['evolution','↗','Build'],['radar','◌','Radar'],['timeline','│','Timeline'],['archive','≡','Archive']];
export const priorities=[
 {id:'p1',title:'Complete the Academy minimum',detail:'Typing accuracy for twelve minutes, then apply one Applied AI lesson to a release criterion.',urgency:'Prime'},
 {id:'p2',title:'Measure one Alpha One criterion',detail:'Name the criterion, inspect its evidence, record the gap, and avoid an unsupported completion percentage.',urgency:'High'},
 {id:'p3',title:'Protect the mobility window',detail:'Use the clear, warm day deliberately; keep private schedule and movement details outside public source.',urgency:'Ongoing'}];
export const courses=[
 {id:'ai',name:'Applied AI',mission:'Build with the system',lesson:'Evidence-based evaluation',status:'Local state only',neglect:'Unknown'},
 {id:'finance',name:'Financial Intelligence',mission:'Money Tree',lesson:'Margin under energy pressure',status:'Local state only',neglect:'Unknown'},
 {id:'spanish',name:'Spanish',mission:'Everyday fluency',lesson:'High-frequency speaking loop',status:'Local state only',neglect:'Unknown'},
 {id:'typing',name:'Typing',mission:'Frictionless input',lesson:'Accuracy before speed',status:'Local state only',neglect:'Priority'}];
export const intelligence=[
 {id:'i1',category:'World',title:'A second trade chokepoint is entering the energy-risk chain',summary:'AP reports a Houthi threat against Saudi-linked shipping through Bab el-Mandeb while Gulf producers accelerate routes that bypass Hormuz.',why:'Two stressed maritime passages can move fuel, freight, insurance and delivery assumptions together.',consequence:'Longer routes and risk premiums can reach landed material costs even when headline oil briefly stabilizes.',action:'Keep quote validity short, verify freight exposure and preserve supplier alternatives.',confidence:'High',freshness:'Jul 24 · 05:01 EDT',state:'Live source checked',source:'https://apnews.com/article/4e25fbdad821762e478173e6308884fb'},
 {id:'i2',category:'Business',title:'The Fed boundary still favors cash discipline',summary:'The July Monetary Policy Report says inflation remains elevated, activity is solid and the policy range has stayed at 3.50%–3.75%.',why:'A plan that depends on rapid rate relief is still a fragile plan.',consequence:'Customer affordability, financing cost and working-capital timing remain material operating variables.',action:'Protect cash conversion and make financing assumptions explicit before commitments.',confidence:'High',freshness:'Fed report · Jul 10',state:'Live source checked',source:'https://www.federalreserve.gov/monetarypolicy/2026-07-mpr-summary.htm'},
 {id:'i3',category:'Weather',title:'Western Connecticut opens clear and warms into the low 80s',summary:'54°F and clear at retrieval; mostly sunny with an 81°F high and 54°F low.',why:'The day supports early movement and reliable travel posture without a storm constraint.',consequence:'Physical tasks are easiest before the warmer afternoon; hydration stays simple and steady.',action:'Use light layers early, move before peak warmth and preserve one uninterrupted Academy/build block.',confidence:'High',freshness:'Jul 24 · 05:01 EDT',state:'Live source checked',source:'https://www.weather.gov/okx/'},
 {id:'i4',category:'Markets',title:'Risk proxies are lower before the U.S. session',summary:'Indicative retrieval: SPY $738.18 (−1.20%), QQQ $691.96 (−1.88%), DIA $516.26 (−1.01%); Bitcoin $65,256 (−0.59%).',why:'Broad weakness reinforces the need to separate market mood from verified demand and cost evidence.',consequence:'Technology sensitivity and financing caution may tighten together while energy risk persists.',action:'Recheck authoritative quotes after the open; make no operating decision from one pre-market snapshot.',confidence:'Medium',freshness:'Jul 24 · 08:48 UTC',state:'Live source checked',source:'https://finance.yahoo.com/quote/SPY/'},
 {id:'i5',category:'Sports',title:'Yankees open the Philadelphia series tonight',summary:'MLB lists Yankees at Phillies at 6:45 PM EDT on Apple TV; the current scoreboard lists Will Warren versus Jesús Luzardo.',why:'This is the one meaningful New York sports window on the calendar.',consequence:'The game can be a deliberate evening choice rather than ambient distraction.',action:'Watch if it supports recovery; otherwise use a short recap and keep the evening light.',confidence:'High',freshness:'MLB · Jul 24',state:'Live source checked',source:'https://www.mlb.com/gameday/yankees-vs-phillies/2026/07/24/823434'},
 {id:'i6',category:'Water Cooler',title:'AI adoption is becoming an evidence problem',summary:'Google launched its first AI & Economy ATLAS report, emphasizing empirical study of how people actually use AI across work and daily life.',why:'The conversation is shifting from capability demos to measurable adoption, task fit and economic value.',consequence:'Alpha One needs usefulness evidence and release criteria—not a theatrical percentage.',action:'Conversation angle: “The next AI moat may be proof of useful behavior, not another benchmark.”',confidence:'High',freshness:'Google · Jul 23',state:'Live source checked',source:'https://blog.google/innovation-and-ai/technology/research/understanding-the-ai-economy/'}];
export const entertainment=[
 {id:'film',type:'FILM / TONIGHT',title:'The Dink · Apple TV',why:'A light underdog comedy about changing games and identity—timely recovery after an evidence-heavy day.',state:'Live now · Apple TV',watchUrl:'https://tv.apple.com/us/movie/the-dink/umc.cmc.5tugaz9vt498ajn7q64ypaqxn',previewUrl:'https://www.youtube.com/watch?v=YyVNFzx5Pl8'},
 {id:'music',type:'XMI / SONG OF THE DAY',title:'“Lovely Day” · Bill Withers',why:'Steady, familiar optimism for a clear Friday morning.',state:'Demonstration data'},
 {id:'longform',type:'LONG-FORM / OPERATOR',title:'Steve Jobs · Stanford commencement',why:'A concise reflection on connecting decisions over time; use it as deliberate wind-down.',state:'Demonstration data'}];
export const risks=[
 {type:'risk',scope:'BUSINESS',level:'High',title:'Dual shipping chokepoints can widen cost uncertainty',body:'Hormuz disruption plus Bab el-Mandeb threats can compound energy, freight and insurance pressure.',action:'Revalidate landed cost and shorten quote validity where exposure is real.'},
 {type:'risk',scope:'SYSTEM',level:'High',title:'A percentage can outrun the evidence',body:'Alpha One architecture and repository runtime are maturing faster than hosted production proof.',action:'Score explicit release criteria only after implementation, tests, synchronization and deployment evidence.'},
 {type:'opp',scope:'STRATEGIC',level:'Now',title:'New evaluation and tracing contracts fit the Alpha One question',body:'Repository-tested XET, XEE and XWR capabilities create a stronger path from activity to auditable evidence.',action:'Apply one bounded evidence rule to Daily Bread and record the result without claiming external production maturity.'}];
export const timeline=[['Now','Orient, hydrate and select one Alpha One criterion'],['Next','Academy minimum · Typing 12 minutes + Applied AI 8 minutes'],['Morning','Inspect criterion, implementation, tests and evidence'],['Midday','Recheck markets, costs and commitments'],['Afternoon','Publish, validate and verify the immutable release'],['Evening','Yankees–Phillies or one deliberate XMI recovery session'],['Wind-down','Record the evidence gap and exact next continuation']];
export const evolution=[
 {metric:'2.6.0',title:'Current edition',body:'July 24 intelligence, Academy prime directive, Alpha One evidence loop and immutable repository archive.',status:'Repository-backed'},
 {metric:'XAOA-001',title:'Alpha One activation controller',body:'Daily Bread now inherits an evidence-gated activation program; usage and usefulness outcomes remain pending.',status:'Repository-backed'},
 {metric:'XCC-002',title:'Repository-first synchronization',body:'Memory is context, not runtime evidence; cross-repository claims fail closed when synchronization cannot be verified.',status:'Inherited active'},
 {metric:'P1 + P2',title:'Competitive runtime phases',body:'XWC/XCE/XOR/XCF and XET/XEE/XWB/XPSDK/XWR are repository-implemented and locally tested in canonical authority.',status:'External production pending'},
 {metric:'XRI-006',title:'Alpha One current gate',body:'The activation controller blocks every successor until XRI-006 carries passing evidence; architecture alone is not completion.',status:'Evidence required'},
 {metric:'0%',title:'Unsupported completion claimed',body:'No Alpha One percentage is published until explicit release criteria produce a defensible calculation.',status:'Warden rule'}];
