export const MIRROR_TIMEZONE='America/New_York';
export const mirrorSections=[
['truth','1 · Truth','What actually happened this week?'],['wins','2 · Wins','What moved forward, and what evidence proves it?'],['friction','3 · Friction','Where did momentum slow or break?'],['energy','4 · Energy','What gave energy, and what drained it?'],['learning','5 · Learning','What changed your understanding or capability?'],['relationships','6 · Relationships','Who needs appreciation, repair, or follow-through?'],['stewardship','7 · Stewardship','What needs attention across health, money, home, or responsibilities?'],['alignment','8 · Alignment','Where did actions match—or drift from—purpose?'],['release','9 · Release','What should be stopped, delegated, forgiven, or carried forward?'],['commitment','10 · Next commitment','What single outcome will define the coming week?']];
const parts=(date,timeZone=MIRROR_TIMEZONE)=>Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
export function mirrorWeekKey(date=new Date(),timeZone=MIRROR_TIMEZONE){const p=parts(date,timeZone),d=new Date(`${p.year}-${p.month}-${p.day}T12:00:00Z`),saturday=new Date(d);saturday.setUTCDate(d.getUTCDate()+(6-d.getUTCDay()));return saturday.toISOString().slice(0,10)}
export function emptyMirror(date=new Date()){return {weekKey:mirrorWeekKey(date),status:'NOT_STARTED',currentSection:0,responses:{},startedAt:null,updatedAt:null,completedAt:null,carriedForward:''}}
export function hydrateMirror(value,date=new Date()){const current=mirrorWeekKey(date),m=value&&typeof value==='object'?value:emptyMirror(date);return {...emptyMirror(date),...m,responses:{...(m.responses||{})},missed:Boolean(m.status==='IN_PROGRESS'&&m.weekKey<current)}}
export function mirrorDue(mirror,date=new Date(),timeZone=MIRROR_TIMEZONE){const p=parts(date,timeZone),current=mirrorWeekKey(date,timeZone);return p.weekday==='Sat'||(mirror.status!=='COMPLETED'&&mirror.weekKey<current)}
export function startMirror(mirror,date=new Date()){const current=mirrorWeekKey(date),same=mirror.weekKey===current||mirror.status==='IN_PROGRESS';return {...(same?mirror:emptyMirror(date)),status:'IN_PROGRESS',startedAt:mirror.startedAt||date.toISOString(),updatedAt:date.toISOString(),missed:Boolean(mirror.status==='IN_PROGRESS'&&mirror.weekKey<current)}}
export function updateMirror(mirror,id,value,date=new Date()){const responses={...mirror.responses,[id]:String(value)},firstMissing=mirrorSections.findIndex(([key])=>!responses[key]?.trim());return {...mirror,status:'IN_PROGRESS',responses,currentSection:firstMissing<0?mirrorSections.length:firstMissing,updatedAt:date.toISOString()}}
export function completionGate(mirror){const missing=mirrorSections.filter(([id])=>!mirror.responses[id]?.trim()).map(([id])=>id);return {pass:missing.length===0,missing,completed:mirrorSections.length-missing.length,total:mirrorSections.length}}
export function completeMirror(mirror,date=new Date()){const gate=completionGate(mirror);if(!gate.pass)return {mirror,error:`Complete all ten sections. ${gate.missing.length} remaining.`,gate};return {mirror:{...mirror,status:'COMPLETED',currentSection:mirrorSections.length,completedAt:date.toISOString(),updatedAt:date.toISOString(),missed:false,carriedForward:mirror.responses.commitment.trim()},error:null,gate}}
